[0.082s] Invoking command in '/home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/opt/ros/humble /usr/bin/cmake --build /home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces -- -j4 -l4
[0.228s] -- Found ament_cmake: 1.3.2 (/opt/ros/humble/share/ament_cmake/cmake)
[1.034s] -- Found rclcpp: 16.0.1 (/opt/ros/humble/share/rclcpp/cmake)
[1.224s] -- Found rosidl_generator_c: 3.1.3 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[1.236s] -- Found rosidl_adapter: 3.1.3 (/opt/ros/humble/share/rosidl_adapter/cmake)
[1.265s] -- Found rosidl_generator_cpp: 3.1.3 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[1.315s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[1.392s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.650s] -- Found rmw_implementation_cmake: 6.1.0 (/opt/ros/humble/share/rmw_implementation_cmake/cmake)
[1.658s] -- Found rmw_fastrtps_cpp: 6.2.1 (/opt/ros/humble/share/rmw_fastrtps_cpp/cmake)
[2.589s] -- Using RMW implementation 'rmw_fastrtps_cpp' as default
[3.316s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[4.480s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[4.480s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[4.481s]   interfaces --arguments-file
[4.481s]   /home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces/rosidl_adapter__arguments__interfaces.json
[4.482s]   --output-dir
[4.483s]   /home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces/rosidl_adapter/interfaces
[4.486s]   --output-file
[4.492s]   /home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces/rosidl_adapter/interfaces.idls)
[4.494s]   returned error code 1:
[4.495s] 
[4.496s]   Error processing 'char departure_point 'A'' of 'interfaces/Serveur': 'value
[4.497s]   ''A'' can not be converted to type 'char': must be a valid integer value >=
[4.498s]   0 and <= 255'
[4.499s] 
[4.526s]   Traceback (most recent call last):
[4.530s] 
[4.538s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 716, in parse_primitive_value_string
[4.542s]       value = int(value_string)
[4.547s] 
[4.551s]   ValueError: invalid literal for int() with base 10: "'A'"
[4.558s] 
[4.564s]   
[4.567s] 
[4.571s]   During handling of the above exception, another exception occurred:
[4.574s] 
[4.577s]   
[4.580s] 
[4.583s]   Traceback (most recent call last):
[4.586s] 
[4.589s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 719, in parse_primitive_value_string
[4.593s]       value = int(value_string, 0)
[4.597s] 
[4.600s]   ValueError: invalid literal for int() with base 0: "'A'"
[4.603s] 
[4.606s]   
[4.609s] 
[4.612s]   During handling of the above exception, another exception occurred:
[4.616s] 
[4.619s]   
[4.621s] 
[4.624s]   Traceback (most recent call last):
[4.627s] 
[4.630s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[4.632s]       return _run_code(code, main_globals, None,
[4.636s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[4.637s]       exec(code, run_globals)
[4.637s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[4.638s]       sys.exit(main())
[4.638s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[4.639s]       abs_idl_file = convert_to_idl(
[4.639s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[4.640s]       return convert_msg_to_idl(
[4.640s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[4.641s]       msg = parse_message_string(package_name, input_file.stem, content)
[4.641s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
[4.642s]       fields.append(Field(
[4.642s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 361, in __init__
[4.643s]       self.default_value = parse_value_string(
[4.643s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 594, in parse_value_string
[4.644s]       return parse_primitive_value_string(type_, value_string)
[4.644s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 721, in parse_primitive_value_string
[4.644s]       raise ex
[4.645s] 
[4.645s]   rosidl_adapter.parser.InvalidValue: value ''A'' can not be converted to
[4.646s]   type 'char': must be a valid integer value >= 0 and <= 255
[4.646s] 
[4.647s] Call Stack (most recent call first):
[4.647s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[4.648s]   CMakeLists.txt:27 (rosidl_generate_interfaces)
[4.648s] 
[4.649s] [0m
[4.649s] -- Configuring incomplete, errors occurred!
[4.650s] See also "/home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces/CMakeFiles/CMakeOutput.log".
[4.650s] gmake: *** [Makefile:2259: cmake_check_build_system] Error 1
[4.651s] Invoked command in '/home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/opt/ros/humble /usr/bin/cmake --build /home/pi/autocab/raspberryPI3/ros2_ws/build/interfaces -- -j4 -l4
